/* CODE FOR HASHTAG */
var hrequest;
var hashPos=0;
var hashNeg=0;
var hashNeu=0;
var hTotalPos = 0;
var hTotalNeg = 0;
var hTotalNeutral = 0;
var hashTweetList = [];
var hashLabels=[];
var streamFlag = false;
var doneHashAnalyse = false;
var hQuery = "";

hashEnter = function(event) {
	if (event.keyCode == 13) {
		streamClick();
	}
}


generateHashReport = function() {
	if (!doneHashAnalyse)
		errorSnackBar('Please do some analysis to generate report');
	else {
		var doc = new jsPDF();
		doc.setFont('Times');
		doc.setFontSize(10);
		doc.text(5,10,"This report is generated by the sentdecoder engine for social media based predictive analysis based on your analysis query");
		doc.setFontSize(12);
		doc.setFontType("bold");
		doc.line(0, 15, 300, 15);
		doc.text(10,25,"Hashtag/Query: "+hQuery);
		doc.setFontType("normal");
		doc.text(10,35,"Total tweets collected: "+(hTotalNeg+hTotalPos+hTotalNeutral));
		doc.text(10,42,"Total negative tweets: "+hTotalNeg);
		doc.text(10,49,"Total positive tweets: "+hTotalPos);
		doc.text(10,56,"Total neutral tweets: "+hTotalNeutral);
		var canvas1 = document.getElementById("hashChart");
		var canvas2 = document.getElementById("hashTweets");
		var data1 = canvas1.toDataURL('image/jpeg');
		var data2 = canvas2.toDataURL('image/jpeg');
		var image1 = new Image();
		var image2 = new Image();
		image1.src = data1;
		image2.src = data2;
		doc.setFontType("bold");
		doc.text(10,66,"Emotions Chart");
		doc.setFontType("normal");
		doc.addImage(image1, 'JPEG', 30, 76, 150, 150);
		doc.line(0, 280, 300, 280);
		doc.setFontSize(10);
		doc.text(5,290,"copyright @sentdecoder 2018");
		doc.addPage();
		doc.setFontSize(12);
		doc.setFontType("bold");
		doc.text(10,20,"Emotions Tweets");
		doc.setFontType("normal");
		doc.addImage(image2, 'JPEG', 10, 30, 190, 120);
		doc.line(0, 280, 300, 280);
		doc.setFontSize(10);
		doc.text(5,290,"copyright @sentdecoder 2018");
		doc.save("hash_report_"+Date.now());
	}
	
}

function streamClick()
{
	var btnAnalyze = document.searchHash.hashanalyze.value;
	var hash=document.searchHash.hashtag.value;
	if (hash==null || hash=='') {
		errorSnackBar('Enter a HashTag to Analyze');
	}
	else {
		if (btnAnalyze == 'Stop') {
			streamFlag = false;
		}
		else {
			var progress="<div class='progress' style='width:600px;margin:auto'><div class='indeterminate'></div></div>";
			document.getElementById('hashCharts').innerHTML=progress;
			sendHash();
		}
	}
}

function sendHash()  
{  
doneHashAnalyse = false;
document.searchHash.hashtag.disabled = true;
document.searchHash.isStream.disabled = true;
var hash=document.searchHash.hashtag.value;
hQuery = hash;
var str = document.searchHash.isStream.value;
var btnAnalyze = document.searchHash.hashanalyze.value;
if ((str=='Stream' || str=="Non-Stream")){
	if (str=='Stream'){
		streamFlag = true;
		document.searchHash.hashanalyze.value = 'Stop';
	}
	else if (str=='Non-Stream'){
		document.searchHash.hashanalyze.disabled = true;
	}
	var url="HashAnalysis?hashtag="+encodeURIComponent(hash)+"&isStream="+encodeURIComponent(str);  
	  
	if(window.XMLHttpRequest){  
	hrequest=new XMLHttpRequest();  
	}  
	else if(window.ActiveXObject){  
	hrequest=new ActiveXObject("Microsoft.XMLHTTP");  
	}  
	  
	try  
	{  
	hrequest.onreadystatechange=getHash;
	hrequest.open("GET",url,true);  
	hrequest.send();  
	}  
	catch(e)  
	{  
	alert("Unable to connect to server");  
	} 
}

}  

function getHash()
{
	if(hrequest.readyState==4){
		doneHashAnalyse = true;
		var arr = [];
		var val=hrequest.responseText; 
		var rows = val.split("<br>");
		var i;
		for(i=0;i<rows.length-1;i++){
			value = parseFloat(rows[i]);
			if (value>0)
				hashPos++;
			else if (value<0)
				hashNeg++;
			else
				hashNeu++;
			hashTweetList.push(value);
			hashLabels.push(hashLabels.length+1);
		}
		var allcharts = "<div id='hashChartHolder' class='mdl-cell mdl-cell--4-col' style='text-align:center;box-shadow: 1px 1px 1px 1px #D1D3D5;border:1px solid #D1D3D5'><canvas id='hashChart' width='400px' height='400px' style='margin:auto'></canvas></div><div id='hashTweetHolder' class='mdl-cell mdl-cell--8-col' style='text-align:center;box-shadow: 1px 1px 1px 1px #D1D3D5;border:1px solid #D1D3D5'><canvas id='hashTweets' width='750px' height='400px' style='margin:auto'></canvas></div>";
		var charts = document.getElementById("hashCharts");
		charts.innerHTML = allcharts;
		plotHashEmotion();
		plotHashTweets();
		document.getElementById('hashCharts').scrollIntoView();
		if (streamFlag) {
			sendHash();
		}
		else {
			hTotalPos = hashPos;
			hTotalNeg = hashNeg;
			hTotalNeutral = hashNeu;
			document.searchHash.hashanalyze.value = 'Analyze';
			hashTweetList = [];
			hashLabels = [];
			hashPos = 0;
			hashNeg = 0;
			hashNeu = 0;
			document.searchHash.hashtag.disabled = false;
			document.searchHash.isStream.disabled = false;
			document.searchHash.hashanalyze.disabled = false;
		}
	}
}

function plotHashEmotion()
{
	document.getElementById("hashChart").remove();
	document.getElementById('hashChartHolder').innerHTML="<canvas id='hashChart' width='400px' height='400' style='margin:auto'>";
	var ctx = document.getElementById('hashChart').getContext('2d');
	Chart.plugins.register({
		beforeDraw: function(chartInstance) {
		var context = chartInstance.chart.ctx;
		context.fillStyle = "white";
		context.fillRect(0, 0, chartInstance.chart.width, chartInstance.chart.height);
		}
		});
	data = {
		    datasets: [{
		        data: [hashPos, hashNeu, hashNeg],
		     	backgroundColor: [
			'#0AF1BC','#F3F1B4','#F66627'	
			]
		    }],

		    // These labels appear in the legend and in the tooltips when hovering different arcs
		    labels: [
		        'Positive',
		        'Neutral',
		        'Negative'
		    ]
		};
	var myDoughnutChart = new Chart(ctx, {
	    type: 'doughnut',
	    data: data,
	    options: {
		responsive: false
	    }
	});
}

function plotHashTweets()
{
	document.getElementById("hashTweets").remove();
	document.getElementById('hashTweetHolder').innerHTML="<canvas id='hashTweets' width='750px' height='400' style='margin:auto'>";
	var ctx = document.getElementById('hashTweets').getContext('2d');
	var chart = new Chart(ctx, {	    
		type: 'line',
	    data: {
	        labels: hashLabels,
	        datasets: [{
	        	label: 'Hash Sentiment',
				borderColor: '#27ABF6',
	            data: hashTweetList,
	            borderWidth: 1
	        }]
	    },

	    // Configuration options go here
	    options: {
	    	responsive:false,
	    }
	});
}
