/* CODE FOR PRODUCT */
var prequest;
var pTotalNeg = 0;
var pTotalPos = 0;
var pTotalNeutral = 0;
var bProductQuery = "";
var pQuery = "";
var doneProductAnalyse = false;

productEnter = function(event) {
	if (event.keyCode == 13) {
		sendProduct();
	}
}

generateProductReport = function() {
	if (!doneProductAnalyse)
		errorSnackBar('Please do some analysis to generate report');
	else {
		var doc = new jsPDF();
		doc.setFont('Times');
		doc.setFontSize(10);
		doc.text(5,10,"This report is generated by the sentdecoder engine for social media based predictive analysis based on your analysis query");
		doc.setFontSize(12);
		doc.setFontType("bold");
		doc.line(0, 15, 300, 15);
		if (bProductQuery!="" && bProductQuery!=null)
			doc.text(10,25,"Product/Brand Name: "+pQuery.toUpperCase()+"/"+bProductQuery.toUpperCase());
		else
			doc.text(10,25,"Product Name: "+pQuery.toUpperCase());
		doc.setFontType("normal");
		doc.text(10,35,"Total tweets collected: "+(bTotalNeg+bTotalPos+bTotalNeutral));
		doc.text(10,42,"Total negative tweets: "+bTotalNeg);
		doc.text(10,49,"Total positive tweets: "+bTotalPos);
		doc.text(10,56,"Total neutral tweets: "+bTotalNeutral);
		var canvas1 = document.getElementById("productChart");
		var canvas2 = document.getElementById("productTweet");
		var data1 = canvas1.toDataURL('image/jpeg');
		var data2 = canvas2.toDataURL('image/jpeg');
		var image1 = new Image();
		var image2 = new Image();
		image1.src = data1;
		image2.src = data2;
		doc.setFontType("bold");
		doc.text(10,66,"Emotions Chart");
		doc.setFontType("normal");
		doc.addImage(image1, 'JPEG', 30, 76, 150, 110);
		doc.line(0, 280, 300, 280);
		doc.setFontSize(10);
		doc.text(5,290,"copyright @sentdecoder 2018");
		doc.addPage();
		doc.setFontSize(12);
		doc.setFontType("bold");
		doc.text(10,20,"Emotions Tweets");
		doc.setFontType("normal");
		doc.addImage(image2, 'JPEG', 10, 30, 190, 120);
		doc.line(0, 280, 300, 280);
		doc.setFontSize(10);
		doc.text(5,290,"copyright @sentdecoder 2018");
		doc.save("product_report_"+Date.now());
	}
	
}

function sendProduct(){
	var product = document.searchProduct.productName.value;
	if (product==null || product=='')
		errorSnackBar('Enter a Product Name to Analyze');
	else {
		doneProductAnalyse = false;
		pQuery = product;
		var progress="<div class='progress' style='width:600px;margin:auto'><div class='indeterminate'></div></div>";
		document.getElementById('productCharts').innerHTML=progress;  
		var brand = document.searchProduct.productBrand.value;
		bProductQuery = brand;
		document.searchProduct.productName.disabled = true;
		document.searchProduct.productBrand.disabled = true;
		document.searchProduct.productAnalyze.disabled = true;
		var url="ProductAnalysis?productName="+encodeURIComponent(product)+"&brandName="+encodeURIComponent(brand);  
		  
		if(window.XMLHttpRequest){  
			prequest=new XMLHttpRequest();  
		}  
		else if(window.ActiveXObject){  
			prequest=new ActiveXObject("Microsoft.XMLHTTP");  
		}  
		try  
		{  
			prequest.onreadystatechange=getProduct;  
			prequest.open("GET",url,true);  
			prequest.send();  
		}  
		catch(e)  
		{  
			alert("Unable to connect to server");  
		}  
	}
}

function getProduct()
{
	if(prequest.readyState==4){
		doneProductAnalyse = true;
		document.searchProduct.productName.disabled = false;
		document.searchProduct.productBrand.disabled = false;
		document.searchProduct.productAnalyze.disabled = false;
		var totPos=0;
		var totNeg=0;
		var totNeu=0;
		var productTweetList = [];
		var i;
		var val = prequest.responseText;
		var rows = val.split('<br>');
		for(i=0;i<rows.length-1;i++){
			value = parseFloat(rows[i]);
			if (value>0)
				totPos++;
			else if (value<0)
				totNeg++;
			else
				totNeu++;
			productTweetList.push(value);
		}
		bTotalPos = totPos;
		bTotalNeg = totNeg;
		bTotalNeutral = totNeu;
		var allcharts='<div id="productChartHolder" class="mdl-cell mdl-cell--4-col" style="text-align:center;box-shadow: 1px 1px 1px 1px #D1D3D5;border:1px solid #D1D3D5"><canvas id="productChart" width="400px" height="400px" style="margin:auto"></canvas></div><div id="productTweetHolder" class="mdl-cell mdl-cell--8-col" style="text-align:center;box-shadow: 1px 1px 1px 1px #D1D3D5;border:1px solid #D1D3D5"><canvas id="productTweet" width="750px" height="400px" style="margin:auto"></canvas></div>';
		var charts = document.getElementById("productCharts");
		charts.innerHTML = allcharts;
		plotProductSentiment(totPos,totNeg,totNeu);
		plotProductTweets(productTweetList);
		document.getElementById('productCharts').scrollIntoView();
	}
}

function plotProductSentiment(cPos,cNeg,cNeu){
	document.getElementById("productChart").remove();
	document.getElementById('productChartHolder').innerHTML="<canvas id='productChart' width='400px' height='400' style='margin:auto'>";
	var ctx = document.getElementById('productChart').getContext('2d');
	Chart.plugins.register({
		beforeDraw: function(chartInstance) {
		var context = chartInstance.chart.ctx;
		context.fillStyle = "white";
		context.fillRect(0, 0, chartInstance.chart.width, chartInstance.chart.height);
		}
		});
	var myChart = new Chart(ctx, {
	    type: 'horizontalBar',
	    data: {
	        labels: ["Positive", "Neutral", "Negative"],
	        datasets: [{
	            label: 'Sentiments Graph',
	            data: [cPos,cNeu,cNeg],
	            backgroundColor: [
	                'rgba(255, 99, 132, 0.2)',
	                'rgba(54, 162, 235, 0.2)',
	                'rgba(255, 206, 86, 0.2)'
	            ],
	            borderColor: [
	                'rgba(255,99,132,1)',
	                'rgba(54, 162, 235, 1)',
	                'rgba(255, 206, 86, 1)'
	            ],
	            borderWidth: 1
	        }]
	    },
	    options: {
	    	responsive:false,
	        scales: {
	            xAxes: [{
	                ticks: {
	                    beginAtZero:true
	                }
	            }]
	        }
	    }
	});

}

function plotProductTweets(ptl){
	document.getElementById("productTweet").remove();
	document.getElementById('productTweetHolder').innerHTML="<canvas id='productTweet' width='750px' height='400' style='margin:auto'>";
	var lbls = [];
	var i;
	for(i=0;i<ptl.length;i++){
		lbls.push(i+1);
	}
	var ctx = document.getElementById('productTweet').getContext('2d');
	var chart = new Chart(ctx, {	    
		type: 'line',
	    data: {
	        labels: lbls,
	        datasets: [{
	        	label: 'Hash Sentiment',
				borderColor: '#27ABF6',
	            data: ptl,
	            borderWidth: 1
	        }]
	    },

	    // Configuration options go here
	    options: {
	    	responsive:false,
	    }
	});	
}
